{{- if and .Values.chat.enabled .Values.chat.ingress.enabled }}
{{- $fullName := printf "%s-chat" (include "huggingface-model.fullname" .) -}}
{{- $serviceName := printf "%s-chat" (include "huggingface-model.fullname" .) -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "huggingface-model.labels" . | nindent 4 }}
  {{- with .Values.chat.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.chat.ingress.tls }}
  tls:
    {{- range .Values.chat.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.chat.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $serviceName }}
                port:
                  {{- if .servicePort }}
                  {{- .servicePort | toYaml | nindent 18 }}
                  {{- else }}
                  number: 8080
                  {{- end }}
              {{- if .extendedOptions }}
              {{- .extendedOptions | toYaml | nindent 14 }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
