apiVersion: v2
name: huggingface-model
description: Helm chart for deploy Hugging Face models and chat-ui to Kubernetes cluster. See [Hugging Face models](https://huggingface.co/models)

type: application

version: 0.0.23

